import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { AlertCircle, CheckCircle, FileText, Shield } from 'lucide-react';

export function RegulatoryGlossary() {
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="h-5 w-5 text-primary" />
            Regulatory Terminology Guide
          </CardTitle>
          <CardDescription>
            Understanding the difference between screening and enrollment in clinical trials
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Key Terminology */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold flex items-center gap-2">
              <FileText className="h-4 w-4" />
              Key Terms
            </h3>
            
            <div className="space-y-4">
              <div className="border-l-4 border-blue-500 pl-4 py-2">
                <div className="flex items-start justify-between mb-2">
                  <p className="font-semibold text-blue-900">Screening</p>
                  <Badge variant="outline" className="text-xs">Phase 1</Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  The process of evaluating whether a patient meets all inclusion and exclusion criteria 
                  for a clinical trial. This includes comprehensive assessments, testing, and confirmation 
                  of eligibility before actual enrollment.
                </p>
              </div>

              <div className="border-l-4 border-green-500 pl-4 py-2">
                <div className="flex items-start justify-between mb-2">
                  <p className="font-semibold text-green-900">Enrollment</p>
                  <Badge variant="outline" className="text-xs">Phase 2</Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  The formal process of registering a patient into a clinical trial after they have been 
                  screened and confirmed to meet all eligibility criteria. Enrollment marks the official 
                  start of a patient's participation in the trial.
                </p>
              </div>

              <div className="border-l-4 border-purple-500 pl-4 py-2">
                <div className="flex items-start justify-between mb-2">
                  <p className="font-semibold text-purple-900">AI Match</p>
                  <Badge variant="outline" className="text-xs">Preliminary</Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  A preliminary assessment generated by AI analysis to identify potential patient-protocol 
                  matches. This is NOT a confirmation of eligibility and must be validated by clinical staff 
                  during the screening visit.
                </p>
              </div>

              <div className="border-l-4 border-amber-500 pl-4 py-2">
                <div className="flex items-start justify-between mb-2">
                  <p className="font-semibold text-amber-900">Screening Visit</p>
                  <Badge variant="outline" className="text-xs">Required</Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  A comprehensive in-person assessment where all eligibility criteria are verified through 
                  physical examination, laboratory tests, medical history review, and informed consent process. 
                  This is mandatory before enrollment.
                </p>
              </div>
            </div>
          </div>

          <Separator />

          {/* Clinical Trial Workflow */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold flex items-center gap-2">
              <CheckCircle className="h-4 w-4" />
              Standard Clinical Trial Workflow
            </h3>
            
            <div className="space-y-3">
              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center font-semibold text-sm">
                  1
                </div>
                <div>
                  <p className="font-medium">Pre-Screening (AI Match)</p>
                  <p className="text-sm text-muted-foreground">
                    AI analysis identifies potential matches based on available patient data
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center font-semibold text-sm">
                  2
                </div>
                <div>
                  <p className="font-medium">CRC Review</p>
                  <p className="text-sm text-muted-foreground">
                    Clinical Research Coordinator reviews match and approves for PI review
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-indigo-100 text-indigo-700 flex items-center justify-center font-semibold text-sm">
                  3
                </div>
                <div>
                  <p className="font-medium">PI Approval</p>
                  <p className="text-sm text-muted-foreground">
                    Principal Investigator provides final approval for patient to proceed to screening
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-amber-100 text-amber-700 flex items-center justify-center font-semibold text-sm">
                  4
                </div>
                <div>
                  <p className="font-medium">Screening Visit</p>
                  <p className="text-sm text-muted-foreground">
                    <strong>Required in-person visit</strong> to confirm all eligibility criteria per protocol
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-green-100 text-green-700 flex items-center justify-center font-semibold text-sm">
                  5
                </div>
                <div>
                  <p className="font-medium">Enrollment</p>
                  <p className="text-sm text-muted-foreground">
                    Patient is officially enrolled after successful screening and informed consent
                  </p>
                </div>
              </div>
            </div>
          </div>

          <Separator />

          {/* Regulatory Guidelines */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold flex items-center gap-2">
              <AlertCircle className="h-4 w-4" />
              ICH-GCP Requirements
            </h3>
            
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 space-y-2">
              <p className="font-semibold text-amber-900 text-sm">Protocol Deviation Prevention</p>
              <ul className="text-sm text-amber-800 space-y-1 list-disc list-inside">
                <li>All inclusion/exclusion criteria must be verified during screening visit</li>
                <li>AI matches are preliminary and do not replace clinical assessment</li>
                <li>Documentation of eligibility confirmation is required in source documents</li>
                <li>Informed consent must be obtained before any study-specific procedures</li>
                <li>Principal Investigator maintains final responsibility for eligibility determination</li>
              </ul>
            </div>
          </div>

          <Separator />

          {/* Important Reminders */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <p className="font-semibold text-blue-900 mb-2">Remember:</p>
            <ul className="text-sm text-blue-800 space-y-1 list-disc list-inside">
              <li>"Approved for Screening" ≠ "Enrolled in Study"</li>
              <li>Screening visit is mandatory before enrollment</li>
              <li>Always recheck criteria during the screening visit</li>
              <li>Document all eligibility assessments per protocol requirements</li>
              <li>When in doubt, consult the protocol and your IRB guidelines</li>
            </ul>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
